config/routes.rb
Orders::Application.routes.draw do
  devise_for :users

  resources :pedidos do
    member do
      get 'print'
    end
  end

  resources :produtos

  root :to => 'pedidos#index'
end

app/models/cliente.rb
class Cliente < ActiveResource::Base
  self.site = "http://sugarcrmapi.localhost"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :produto
  validates :preco, :presence => true
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :pedido
  validates :meio, :data_prevista, :valor, :presence => true
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  has_many :itens, :dependent => :destroy
  has_many :pagamentos, :dependent => :destroy
  validates :cliente_id, :numero, :previsao_entrega, :presence => true
  validates :numero, :uniqueness => true
  validate :soma_pagamentos_igual_valor_total?
  accepts_nested_attributes_for :itens, :reject_if => lambda { |a| a[:preco].blank? },
                                :allow_destroy => true
  accepts_nested_attributes_for :pagamentos, :reject_if => lambda { |a| a[:valor].blank? },
                                :allow_destroy => true

  def cliente
    Cliente.find(self.cliente_id)
  end

  def cliente=(c)
    self.cliente_id = c.id
  end

  def valor
    total = 0.0
    if not self.itens.empty?
      self.itens.each do |item|
        total += item.preco
      end
    end
    return total
  end

  def valor_pagamentos
    total = 0.0
    if not self.pagamentos.empty?
      self.pagamentos.each do |pagamento|
        total += pagamento.valor
      end
    end
    return total
  end

  def soma_pagamentos_igual_valor_total?
    if valor != valor_pagamentos
      errors.add(:pagamentos, "A soma dos pagamentos deve ser igual ao valor do pedido")
      return false
    end
    return true
  end
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_many :itens
  validates :fabricante, :nome, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedidos }
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/new
  # GET /pedidos/new.json
  def new
    @pedido = Pedido.new
    @pedido.itens.build
    @pedido.pagamentos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/1/edit
  def edit
    @pedido = Pedido.find(params[:id])
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(params[:pedido])

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido criado com sucesso.' }
        format.json { render json: @pedido, status: :created, location: @pedido }
      else
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pedidos/1
  # PUT /pedidos/1.json
  def update
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      if @pedido.update_attributes(params[:pedido])
        format.html { redirect_to @pedido, notice: 'Pedido alterado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url }
      format.json { head :ok }
    end
  end

  # GET /pedidos/1/print
  def print
    @pedido = Pedido.find(params[:id])
    render :layout => false
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_filter :authenticate_user!

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto alterado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_association(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_association(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orders</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <div class="header">
    <%= "Ola, #{current_user.email}!" unless not user_signed_in? %>
    <%= link_to('[Sair]', destroy_user_session_path, :method => :delete) if user_signed_in? %>
  </div>
  <div class="menu">
    <%= link_to 'Produtos', produtos_path %> |
    <%= link_to 'Pedidos', pedidos_path %>
  </div>
</p>
<p>
  <div class="content">
    <%= yield %>
  </div>
</p>
</body>
</html>

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "erro") %>:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br />
    <%= f.select :cliente_id, Cliente.all.collect { |c| [c.nome + ' - ' + c.email, c.id] }, { :include_blank => true } %>
  </div>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero, :size => 8 %>
  </div>
  <div class="field">
    <%= f.label :vendedor %><br />
    <%= f.text_field :vendedor, :size => 16 %>
  </div>
  <div class="field">
    <%= f.label :previsao_entrega %><br />
    <%= f.date_select :previsao_entrega %>
  </div>
  <div class="field">
    <%= f.label :observacao %><br />
    <%= f.text_area :observacao, :rows => 3 %>
  </div>
  <div class="field">
    <h2>Itens</h2>
    <table>
      <tr>
        <th>Produto</th>
        <th>Preco (R$)</th>
        <th>Observacao</th>
        <th class="action"></th>
      </tr>
      <%= f.fields_for :itens do |builder| %>
        <%= render 'item_fields', :f => builder %>
      <% end %>
      <tr colspan="4">
        <td><%= link_to_add_association "Novo item", f, :itens %></td>
      </tr>
    </table>
  </div>
  <div class="field">
    <h2>Pagamentos</h2>
    <table>
      <tr>
        <th>Meio</th>
        <th>Data Prevista</th>
        <th>Evento</th>
        <th>Valor (R$)</th>
        <th class="action"></th>
      </tr>
      <%= f.fields_for :pagamentos do |builder| %>
        <%= render 'pagamento_fields', :f => builder %>
      <% end %>
      <tr colspan="5">
        <td><%= link_to_add_association "Novo pagamento", f, :pagamentos %></td>
      </tr>
    </table>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/_item_fields.html.erb
<tr class="association">
  <td><%= f.select :produto_id, Produto.all.collect { |p| [p.fabricante + ' - ' + p.nome, p.id] },
      { :include_blank => true } %></td>
  <td><%= f.text_field :preco, :size => 15 %></td>
  <td><%= f.text_field :observacao, :size => 40 %></td>
  <td>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Remover", "remove_association(this)" %>
  </td>
</tr>

app/views/pedidos/_pagamento_fields.html.erb
<tr class="association">
  <td><%= f.text_field :meio, :size => 15 %></td>
  <td><%= f.date_select :data_prevista %></td>
  <td><%= f.text_field :evento, :size => 15 %></td>
  <td><%= f.text_field :valor, :size => 15 %></td>
  <td>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Remover", "remove_association(this)" %>
  </td>
</tr>

app/views/pedidos/edit.html.erb
<h1>Editando o pedido</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @pedido %> |
<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listando os pedidos</h1>

<table>
  <tr class="header">
    <th>Cliente</th>
    <th>Numero</th>
    <th>Vendedor</th>
    <th>Prev. de Entrega</th>
    <th>Valor (R$)</th>
    <th class="action"></th>
    <th class="action"></th>
    <th class="action"></th>
  </tr>

<% @pedidos.each do |pedido| %>
  <tr>
    <td><%= pedido.cliente.nome %></td>
    <td><%= pedido.numero %></td>
    <td><%= pedido.vendedor %></td>
    <td><%= pedido.previsao_entrega %></td>
    <td><%= pedido.valor %></td>
    <td><%= link_to 'Mostrar', pedido %></td>
    <td><%= link_to 'Editar', edit_pedido_path(pedido) %></td>
    <td><%= link_to 'Remover', pedido, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>Novo pedido</h1>

<%= render 'form' %>

<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/print.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orders</title>
  <style>
    body, input {
      font-family: verdana, arial, helvetica, sans-serif;
      font-size: 13px;
    }
    th, td {
      padding: 0px 10px 0px 10px;
    }
    input {
      border: none;
    }
  </style>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Pedido <%= @pedido.numero %></h1>

  <p>
    <b>Data:</b>
    <%= @pedido.created_at.to_formatted_s(:db) %>
    <b>Previsao de Entrega:</b>
    <%= @pedido.previsao_entrega %>
  </p>

  <p>
    <fieldset>
      <legend>Cliente</legend>
      <table>
        <tr>
          <td><b>Nome:</b></td>
          <td><%= @pedido.cliente.nome %></td>
          <td><b>R. Social:</b></td>
          <td><%= @pedido.cliente.razao_social %></td>
        </tr>
        <tr>
          <td><b>CNPJ:</b></td>
          <td><%= @pedido.cliente.cnpj %></td>
          <td><b>IE:</b></td>
          <td><%= @pedido.cliente.ie %></td>
        </tr>
        <tr>
          <td><b>Endereco:</b></td>
          <td><%= @pedido.cliente.endereco %></td>
          <td><b>Telefone:</b></td>
          <td><%= @pedido.cliente.telefone %></td>
        </tr>
        <tr>
          <td><b>Email:</b></td>
          <td><%= @pedido.cliente.email %></td>
          <td><b>Website:</b></td>
          <td><%= @pedido.cliente.website %></td>
        </tr>
      </table>
    </fieldset>
  </p>

  <p>
    <fieldset>
      <legend>Itens</legend>
      <table>
        <tr>
          <th>Fabricante</th>
          <th>Produto</th>
          <th>Preco</th>
          <th>Observacao</th>
        </tr>
        <% @pedido.itens.each do |item| %>
        <tr>
          <td><%= item.produto.fabricante %></td>
          <td><%= item.produto.nome %></td>
          <td><%= item.preco %></td>
          <td><%= item.observacao %></td>
        </tr>
        <% end %>
      </table>
    </fieldset>
  </p>

  <p>
    <fieldset>
      <legend>Pagamentos</legend>
      <table>
        <tr>
          <th>Meio</th>
          <th>Data Prevista</th>
          <th>Evento</th>
          <th>Valor (R$)</th>
        </tr>
        <% @pedido.pagamentos.each do |pagamento| %>
        <tr>
          <td><%= pagamento.meio %></td>
          <td><%= pagamento.data_prevista %></td>
          <td><%= pagamento.evento %></td>
          <td><%= pagamento.valor %></td>
        </tr>
        <% end %>
      </table>
    </fieldset>
  </p>

  <p>
    <b>TOTAL:</b>
    R$ <%= @pedido.valor %>
  </p>

  <p>
    <b>Informacoes para deposito:</b><br />
    Favorecido: <input type="text" size=70 value="Curvatub Comercio e Importacao de Maquinas Ltda"><br />
    Banco: <input type="text" size=4>
    Agencia: <input type="text" size=6>
    Conta Corrente: <input type="text" size=15><br />
  </p>

  <p>
    <b>Observacao:</b>
    <%= @pedido.observacao %>
  </p>

  <br /><br /><br />

  <p>
    <table width="100%">
      <tr>
        <td>___________________________________</td>
        <td style="text-align:right;">___________________________________</td>
      </tr>
      <tr>
        <td>
          <%= @pedido.cliente.nome %><br />
          <%= @pedido.cliente.cnpj %>
        </td>
        <td style="text-align:right;">
          <input type="text" size=26 style="text-align:right;" value="Curvatub Com. e Imp. de Maquinas"><br />
          <input týpe="text" size=19 style="text-align:right;" value="10.548.995/0002-64">
        </td>
    </table>
  </p>

  <br /><br /><br />

  <p style="border-top:1px solid">
    <input type="text" size=100 value="Curvatub Comercio e Importacao de Maquinas Ltda"><br />
    <input type="text" size=100 value="Av. Santa Catarina, 2970 - Vila Mascote"><br />
    <input type="text" size=100 value="Sao Paulo / SP / Brasil"><br />
    <input type="text" size=100 value="+55 (11) 5565-7855"><br />
    <input type="text" size=100 value="http://www.curvatub.com.br">
  </p>
</body>
</html>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedido</h1>

<p>
  <b>Numero:</b>
  <%= @pedido.numero %>
</p>

<p>
  <b>Vendedor:</b>
  <%= @pedido.vendedor %>
</p>

<p>
  <b>Previsao de Entrega:</b>
  <%= @pedido.previsao_entrega %>
</p>

<p>
  <b>Valor:</b>
  <%= @pedido.valor %>
</p>

<p>
  <b>Observacao:</b>
  <%= @pedido.observacao %>
</p>

<h2>Cliente</h2>

<p>
  <b>Nome:</b>
  <%= @pedido.cliente.nome %>
</p>

<p>
  <b>Razao Social:</b>
  <%= @pedido.cliente.razao_social %>
</p>

<p>
  <b>CNPJ:</b>
  <%= @pedido.cliente.cnpj %>
</p>

<p>
  <b>Inscricao Estadual:</b>
  <%= @pedido.cliente.ie %>
</p>

<p>
  <b>Endereco:</b>
  <%= @pedido.cliente.endereco %>
</p>

<p>
  <b>Telefone:</b>
  <%= @pedido.cliente.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @pedido.cliente.email %>
</p>

<p>
  <b>Website:</b>
  <%= @pedido.cliente.website %>
</p>

<h2>Itens</h2>

<p>
  <table>
    <tr>
      <th>Fabricante</th>
      <th>Produto</th>
      <th>Preco</th>
      <th>Observacao</th>
    </tr>
    <% @pedido.itens.each do |item| %>
    <tr>
      <td><%= item.produto.fabricante %></td>
      <td><%= item.produto.nome %></td>
      <td><%= item.preco %></td>
      <td><%= item.observacao %></td>
    </tr>
    <% end %>
  </table>
</p>

<h2>Pagamentos</h2>

<p>
  <table>
    <tr>
      <th>Meio</th>
      <th>Data Prevista</th>
      <th>Evento</th>
      <th>Valor (R$)</th>
    </tr>
    <% @pedido.pagamentos.each do |pagamento| %>
    <tr>
      <td><%= pagamento.meio %></td>
      <td><%= pagamento.data_prevista %></td>
      <td><%= pagamento.evento %></td>
      <td><%= pagamento.valor %></td>
    </tr>
    <% end %>
  </table>
</p>

<%= link_to 'Editar', edit_pedido_path(@pedido) %> |
<%= link_to 'Imprimir', print_pedido_path(@pedido) %> |
<%= link_to 'Voltar', pedidos_path %>

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "erro") %>:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fabricante %><br />
    <%= f.text_field :fabricante %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Alterando o produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listando os produtos</h1>

<table>
  <tr>
    <th>Fabricante</th>
    <th>Nome</th>
    <th class="action"></th>
    <th class="action"></th>
    <th class="action"></th>
  </tr>

<% @produtos.each do |produto| %>
  <tr>
    <td><%= produto.fabricante %></td>
    <td><%= produto.nome %></td>
    <td><%= link_to 'Mostrar', produto %></td>
    <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
    <td><%= link_to 'Remover', produto, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Produto</h1>

<p>
  <b>Fabricante:</b>
  <%= @produto.fabricante %>
</p>

<p>
  <b>Nome:</b>
  <%= @produto.nome %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>